export const LANGUAGE_EXTENSIONS: Record<string, string> = {
  // Programming languages (subset for office usage)
  ".ts": "typescript",
  ".tsx": "typescriptreact",
  ".js": "javascript",
  ".jsx": "javascriptreact",
  ".py": "python",
  ".rb": "ruby",
  ".go": "go",
  ".rs": "rust",
  ".java": "java",
  ".cpp": "cpp",
  ".c": "c",
  ".h": "c",
  ".cs": "csharp",
  ".swift": "swift",
  ".kt": "kotlin",
  ".php": "php",
  // Office documents
  ".md": "markdown",
  ".txt": "text",
  ".json": "json",
  ".xml": "xml",
  ".html": "html",
  ".css": "css",
  // Config files
  ".yaml": "yaml",
  ".yml": "yaml",
  ".toml": "toml",
  ".ini": "ini",
  ".env": "bash",
  ".sh": "bash",
  ".zsh": "bash",
  ".bat": "batch",
  ".ps1": "powershell",
  // Data
  ".csv": "csv",
  ".sql": "sql",
}
